cbvproject3/cbvproject3/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookview/',views.BookListView.as_view()),
]

cvbproject2/cvbproject2/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', views.bookslistview.as_view()),
    path('bookslist/', views.bookslistview2.as_view()),
    path('<int:pk>/', views.bookdetailview.as_view()),

                                                                                                                                                                                               

]

newsproject/newsproject/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.info),
    path('movies/', views.movies),
    path('sports/', views.sports),
    path('politics/', views.politics),


]

cbvproject3/testapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=30)
    author=models.CharField(max_length=30)
    pages=models.IntegerField()
    price=models.FloatField()

cvbproject2/testapp/models.py
from django.db import models

# Create your models here.
class Books(models.Model):
    title=models.CharField(max_length=30)
    author=models.CharField(max_length=30)
    pages=models.IntegerField()
    price=models.FloatField()

cbvproject3/testapp/views.py
from django.shortcuts import render
from django.views.generic import ListView
from testapp.models import Book
# Create your views here.
class BookListView(ListView):
    model=Book

cvbproject2/testapp/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from testapp.models import Books
# Create your views here.
# for only listview
class bookslistview(ListView):
    model=Books
    template_name='testapp/books.html'
    context_object_name="books"    #model
class bookslistview2(ListView):
    model=Books
    template_name='testapp/books.html'
    context_object_name="books"
# for only detailview for perticular record we use   default 
class bookdetailview(DetailView): 
    model=Books
    template_name='testapp/books_details.html'
    context_object_name="books"

    

newsproject/testapp/views.py
from django.shortcuts import render

# Create your views here.
def info(request):
    return render(request,'testapp/wish.html')
def movies(request):
    head="Movies Information"
    s1="OG will come......"
    s2="GAME Changer will come....."
    s3="DEVARA will come..."
    type="movies"
    my_dict={"head":head,"s1":s1,"s2":s2,'s3':s3,"type":type}
    return render(request,'testapp/news.html',my_dict)

def sports(request):
    head="Sports Information"
    s1="81st runs...."
    s2="khohli runs 200....."
    s3="nest IPL  march 2025..."
    type="sports"
    my_dict={"head":head,"s1":s1,"s2":s2,'s3':s3,"type":type}
    return render(request,'testapp/news.html',my_dict)
def politics(request):
    head="politics Information"
    s1="cm chandrababu...."
    s2="duputy cm pawan kalyan....."
    s3="next cm?????..."
    type="politics"
    my_dict={"head":head,"s1":s1,"s2":s2,'s3':s3,"type":type}
    return render(request,'testapp/news.html',my_dict)

cbvproject3/templates/testapp/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <h1>this my cvb project3</h1>
        <h2>all books  information</h2>
        {%  for book in book_list %}
            <li>Title:<strong>{{book.title}}</strong></li>
            <li>author:<strong>{{book.author}}</strong></li>
            <li>pages:<strong>{{book.pages}}</strong></li>
            <li>price:<strong>{{book.price}}</strong></li>
        <hr>
        {% endfor %}
</body>
</html>

cvbproject2/templates/testapp/Books_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<body>
    <h1>this is books infromation</h1>
    <div class='container'>
        {% for book in book_list %}     <!-- here in this for loop book=object book_list = or modelname=books we can use (books_list or book_list)mondatary-->
        <ul>
            <li>Title:<strong>{{book.title}}</strong></li>
            <li>author:<strong>{{book.author}}</strong></li>
            <li>pages:<strong>{{book.pages}}</strong></li>
            <li>price:<strong>{{book.price}}</strong></li>
        </ul>
        <hr>
        {% endfor %}
    </div>
</body>
</html>

cvbproject2/templates/testapp/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<body>
    <h1>this is books infromation custimzed template file</h1>
    <h2><center>detail for books</center></h2>
    <!--<div class='container'>
        {% for book in books %}
            <ul>
            <li>Title:<strong>{{book.title}}</strong></li>
            <li>author:<strong>{{book.author}}</strong></li>
            <li>pages:<strong>{{book.pages}}</strong></li>
            <li>price:<strong>{{book.price}}</strong></li>
            </ul>
        <hr>
        </ol>
        {% endfor %}    
    </div>-->
    <div class="container">
        <ol>
           {% for book in books%}
           <li><a href="/{{book.id}}">{{book.title}}</a></li>
           {% endfor %}
        </ol>
    </div>
</body>
</html>

cvbproject2/templates/testapp/books_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<!--books==contestparametrs--> 
<body>
    <div class="container">
        <h1>{{books.title}} infromation </h1>
        <ul>
           <li>Title:<strong>{{books.title}}</strong></li>
           <li>author:<strong>{{books.author}}</strong></li>
           <li>pages:<strong>{{books.pages}}</strong></li>
           <li>price:<strong>{{books.price}}</strong></li>
        </ul>
    </div>
</body>
</html>

newsproject/templates/testapp/news.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/demo.css'%}">
</head>
<body>
    <h1>{{head}}</h1>
    <ul>
    <li>{{s1}}</li>
    <li>{{s2}}</li>
    <li>{{s3}}</li>
    </ul>
    {% if type == 'movies' %}
    <img src="{%static 'images/1.jpg'%}" alt="upload soon">
    <img src="{%static 'images/2.jpg'%}" alt="upload soon">
    <img src="{%static 'images/3.jpg'%}" alt="upload soon">
    <img src="{%static 'images/4.jpg'%}" alt="upload soon">

    {% elif type == 'sports' %}
    <img src="{%static 'images/8.jpg'%}" alt="upload soon">
    <img src="{%static 'images/9.jpg'%}" alt="upload soon">
    <img src="{%static 'images/10.jpg'%}" alt="upload soon">
    {%elif type == 'politics' %}
    <img src="{%static 'images/5.jpg'%}" alt="upload soon">
    <img src="{%static 'images/6.jpg'%}" alt="upload soon">
    <img src="{%static 'images/7.jpg'%}" alt="upload soon">
    {%endif%}
</body>
</html>

newsproject/templates/testapp/wish.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/demo.css'%}">
</head>
<body>
    <h1>welcome to the VV channel</h1>
    <img src="{%static 'images/news.jpg'%}" alt="upload soon">
    <ul>
        <li><a href="/movies">Movies Information</a></li>
        <li><a href="/sports">Sports Information</a></li></li>
        <li><a href="/politics">Politics Information</a></li></li>
    </ul>
</body>
</html>